
server:
  port: 9091


dubbo:
  application:
    name: search_service
  registry:
    address: zookeeper://192.168.96.128:2181
  protocol:
    port: 20881
    name: dubbo
  consumer:
    check: false


spring:
  data:
    solr:
      host: http://192.168.96.128:8080/solr
